apiVersion: v1
description: A Helm chart for Activiti Cloud Full Example
icon: https://raw.githubusercontent.com/Activiti/activiti.github.io/master/mstile-150x150.png
kubeVersion: '>=1.15.0-0'
name: activiti-cloud-full-example
sources:
- https://github.com/Activiti/activiti-cloud-full-chart
version: 7.1.0-M13
