dependencies:
  - name: "keycloak"
    repository: "https://codecentric.github.io/helm-charts"
    version: "9.5.0"
    condition: "application.activiti-cloud-identity.enabled,activiti-cloud-identity.enabled"
    alias: "activiti-cloud-identity"
  - name: "rabbitmq"
    repository: "https://charts.bitnami.com/bitnami"
    version: "7.8.0"
    condition: "application.rabbitmq.enabled,rabbitmq.enabled"
  - name: "postgresql"
    repository: "https://charts.bitnami.com/bitnami"
    version: "9.1.1"
    condition: "application.postgresql.enabled,postgresql.enabled"
  - name: "common"
    repository: "https://activiti.github.io/activiti-cloud-helm-charts"
    version: "7.1.0-M13"
    condition: "activiti-cloud-modeling.enabled,modeling.enabled"
    alias: "activiti-cloud-modeling"
  - name: "common"
    repository: "https://activiti.github.io/activiti-cloud-helm-charts"
    version: "7.1.0-M13"
    condition: "activiti-modeling-app.enabled,modeling.enabled"
    alias: "activiti-modeling-app"
  # - name: "common"
  #   repository: "https://hub.docker.com/repository/docker/aeowlian/satunol-runtime-bundle"
  #   version: "0.4"
  #   condition: "application.runtime-bundle.enabled,runtime-bundle.enabled"
  #   alias: "runtime-bundle"
  - name: "common"
    repository: "https://activiti.github.io/activiti-cloud-helm-charts"
    version: "7.1.0-M13"
    condition: "application.activiti-cloud-query.enabled,activiti-cloud-query.enabled"
    alias: "activiti-cloud-query"
  - name: "common"
    repository: "https://activiti.github.io/activiti-cloud-helm-charts"
    version: "7.1.0-M13"
    condition: "application.activiti-cloud-connector.enabled,activiti-cloud-connector.enabled"
    alias: "activiti-cloud-connector"
  - name: satunol-runtime-bundle
    repository: https://raw.githubusercontent.com/jy006/satunol-helm-repo/master/
    version: 0.1.0
    alias: "runtime-bundle"
